### ISSUE TITLE
RogueViz

### ISSUE THREAD

**Issue by zenorogue** [lateral/crystal-ball#1]
Have you seen our [RogueViz](http://roguetemple.com/z/hyper/rogueviz.php)? It seems to do very similar work, including moving points and computing embedding likelihoods [(demo)](https://www.mimuw.edu.pl/~erykk/dhrg/index.html?c=-7+-palrgba+gridt+0xFF000040+-palrgba+gridr+0xFF000080+-palrgba+grido+0xFF000010+-expansion+1+1+7+-expansion-off+-canvas+i+-canvas+00FF00+-canvas+M+-ggamma+2+-lab+-graph+fit+-noplayer+--msg0), and it is not cited.

**Comment by benjaminwilson** [comment]
Hi, I hadn't seen the demo! Certainly I will add it to the list of
citations. I am a big fan of hyperrogue, I have mentioned it already talks.
Very nice work!

**Comment by zenorogue** [comment]
Thanks! 

Maybe I should add that the demo is actually for our (yet unpublished) paper about discrete embeddings which is not linked back from the demo, here it is: [arXiv](https://arxiv.org/abs/1707.01124)

**Comment by benjaminwilson** [comment]
@zenorogue I'm not sure that I got the order of the co-authors right?

**Comment by eryxcc** [comment]
I think putting Dorota first would be more appropriate here (she is the first author for RogueViz stuff, and I am for HyperRogue/algorithmic stuff). Thanks!
